-- MySQL Script generated by MySQL Workbench
-- 04/16/17 15:40:03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema agnss
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema agnss
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `agnss` DEFAULT CHARACTER SET utf8 ;
USE `agnss` ;

-- -----------------------------------------------------
-- Table `agnss`.`agnss`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `agnss`.`agnss` (
  `device` VARCHAR(45) NOT NULL,
  `updated` DATETIME NULL,
  `basetime` INT NULL,
  `flag` INT NULL,
  `year` INT NULL,
  `month` INT NULL,
  `day` INT NULL,
  `hour` INT NULL,
  `minute` INT NULL,
  `sec` INT NULL,
  `minsec` INT NULL,
  `secacc` DOUBLE NULL,
  `lat` DOUBLE NULL,
  `lon` DOUBLE NULL,
  `alt` DOUBLE NULL,
  `posacc` DOUBLE NULL,
  `bdsmask_low` INT NULL,
  `bdsmask_high` INT NULL,
  `gpsmask` INT NULL,
  `aidini_gps` VARCHAR(255) NULL,
  `aidini_bds` VARCHAR(255) NULL,
  `aidini_gpsbds` VARCHAR(255) NULL,
  `aideph_gps` VARCHAR(4000) NULL,
  `aideph_bds` VARCHAR(4000) NULL,
  `aideph_gpsbds` VARCHAR(8000) NULL,
  PRIMARY KEY (`device`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `agnss`.`agnss_record`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `agnss`.`agnss_record` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `device` VARCHAR(45) NULL,
  `updated` DATETIME NULL,
  `basetime` INT NULL,
  `flag` INT NULL,
  `year` INT NULL,
  `month` INT NULL,
  `day` INT NULL,
  `hour` INT NULL,
  `minute` INT NULL,
  `sec` INT NULL,
  `minsec` INT NULL,
  `secacc` DOUBLE NULL,
  `lat` DOUBLE NULL,
  `lon` DOUBLE NULL,
  `alt` DOUBLE NULL,
  `posacc` DOUBLE NULL,
  `bdsmask_low` INT NULL,
  `bdsmask_high` INT NULL,
  `gpsmask` INT NULL,
  `aidini_gps` VARCHAR(255) NULL,
  `aidini_bds` VARCHAR(255) NULL,
  `aidini_gpsbds` VARCHAR(255) NULL,
  `aideph_gps` VARCHAR(4000) NULL,
  `aideph_bds` VARCHAR(4000) NULL,
  `aideph_gpsbds` VARCHAR(8000) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = 'agnss history record';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
